import { Link } from 'react-router-dom'
import Header from '../components/Header'
import Footer from '../components/Footer'
import '../components/PageStyles.css'

function DigitalBankingTerms() {
  return (
    <div className="page-container">
      <Header />

      {/* Hero */}
      <section className="page-hero">
        <div className="page-hero-overlay"></div>
        <div className="page-hero-content">
          <h1>Digital Banking Terms &amp; Conditions</h1>
          <p>Terms and Conditions Applicable to Digital Banking Channels</p>
        </div>
      </section>

      {/* Breadcrumb */}
      <nav className="breadcrumb">
        <div className="container">
          <Link to="/">Home</Link>
          <span className="separator">/</span>
          <span className="current">Digital Banking Terms &amp; Conditions</span>
        </div>
      </nav>

      {/* Content */}
      <section className="content-section white-section">
        <div className="container">
          <div className="legal-content">

            <p>
              Please read the following Terms and Conditions carefully. By using this website and its related services,
              the customer acknowledges that the customer has read and understood the Terms and Conditions and that the
              customer accepts and will be bound by them, as they may be modified by TN CyberTech Bank Limited (the Bank)
              from time to time, and posted on this website. If the customer does not agree to the Terms and Conditions
              of use, the customer may not use this website.
            </p>

            <h2>1. Definitions</h2>
            <p>In these Terms and Conditions, the following words will have the following meanings:</p>
            <p>
              1.1 <strong>'Digital Banking Channels'</strong> means the service provided by the Bank including and offering the following:
            </p>
            <p>1.2 Obtaining information related to the Account, including transactions and standing instruction;</p>
            <p>1.3 Transferring funds;</p>
            <p>1.4 Paying accounts;</p>
            <p>1.5 Making own defined payments where the Customer provides the beneficiary's details;</p>
            <p>1.6 Requesting from the Bank statements and replies to enquiries which relate to the Account;</p>
            <p>1.7 Creating Stop Orders; and</p>
            <p>1.8 Using any other service, which may be available through Online Banking or Digital Banking Channels.</p>
            <p>1.9 Digital Banking Channels also includes Online Banking, Mobile Banking, WhatsApp Banking and USSD *236# Banking.</p>
            <p>
              1.10 <strong>'Account'</strong> means any facility, arrangement or other transaction platform between the Bank and Customer,
              held or registered in the name of the customer including any such other accounts in respect of which the Customer
              holds a valid Mandate.
            </p>
            <p>1.11 <strong>'Bank'</strong> means TN CyberTech Bank Limited.</p>
            <p>
              1.12 <strong>'Billing Account'</strong> means the Customer's nominated account used for the purpose of debiting the fees
              payable in terms of this agreement.
            </p>
            <p>1.13 <strong>'Commencement Date'</strong> means the date of submission of a signed application for registration.</p>
            <p>1.14 <strong>'Customer'</strong> means the person who has registered to use Digital Banking Channels.</p>
            <p>
              1.15 <strong>'Main User/s'</strong> means the person/s authorized or deemed to be authorized by the Customer to use the
              Digital Banking Channels.
            </p>
            <p>
              1.16 <strong>'Password'</strong> means the alphanumeric (both letters and numbers or any prescribed format) characters
              chosen by the Customer or Main User, as the case may be, used as an additional security and authentication when
              accessing the Digital Banking Channels.
            </p>
            <p>
              1.17 <strong>'PIN'</strong> means numeric digits (Personal Identification Number), chosen by the Customer or Main User and
              used as a security or authentication when accessing the Digital Banking Channels.
            </p>
            <p>
              1.18 <strong>'One Time Pin (OTP)'</strong> is a unique code that acts as a one-time password that is required when performing
              particular transactions on Online Banking which is generated by tokens.
            </p>

            <h2>2. Use of Digital Banking Channels</h2>
            <p>
              2.1 The use of Digital Banking Channels is subject to terms and conditions as provided by the Bank. This agreement
              governs the customer and our rights and obligations when the customer uses or accesses any of the Digital Banking
              Channels. The customer will become bound to the most recent version of this agreement once the customer registers to
              use Digital Banking Channels. Before the customer can use the Digital Banking Channels, the customer must have more
              information on how to register for the different Digital Banking Channels available. To use the Digital Banking Channels,
              the customer must be at least 18 years old or have the customer's parent/legal guardian's consent unless the customer
              is an emancipated minor. By registering to use the Digital Banking Channels the customer must therefore confirm that
              the customer is at least 18 years old or have the customer's parent/guardian's consent or have been emancipated, as
              the case may be.
            </p>
            <p>
              2.2 The customer acknowledges that information transmitted through the Internet or any other communication system,
              including wireless communication system, is susceptible to unlawful access, distortion and monitoring and that the
              Customer uses the Digital Banking Channels at their own risk.
            </p>
            <p>
              2.3 The Customer authorizes the Bank to carry out any and all instructions given via the Digital Banking Channels,
              including the debiting of and transfer of funds from the Account and the furnishing of information on the Account,
              provided that the instructions are authenticated by the use of:
            </p>
            <ul>
              <li>2.3.1 The PIN and/or Password</li>
              <li>2.3.2 Any other procedures which may be agreed on in writing between the Customer and the Bank</li>
            </ul>
            <p>
              2.4 All instructions given by the Customer or any Authorized Signatory are irrevocable and binding on the Customer and
              the Customer authorizes the Bank to carry out any and all instructions given. Such instructions may only be cancelled,
              withdrawn, altered or amended in whole or in part with the Bank's consent.
            </p>
            <p>
              2.5 The Customer is responsible for the accuracy and completeness of all instructions; ensuring that the Bank Account(s)
              have sufficient funds for the Bank to carry out any instruction and making sure that the Customer and each Authorized Signatory:
            </p>
            <ul>
              <li>2.5.1 follow the Bank's instructions in connection with the Bank Account(s) and Service(s);</li>
              <li>2.5.2 comply with all applicable laws; and</li>
              <li>2.5.3 give to the Bank all information required by the Bank for it to comply with the instruction and applicable laws.</li>
              <li>
                2.5.4 The Bank will not be liable for any loss or damage as a result of the Customer's instructions to pay or transfer
                funds being late, inaccurate, inadequate or incomplete; or any third party refusing or delaying to pay or transfer the
                funds to the account of the intended payee.
              </li>
            </ul>
            <p>
              2.6 The provision of the Digital Banking Channels will not entitle the Customer to overdraw the Account if overdraft or
              other borrowing arrangements have not been made and approved by the Bank, or where such arrangements have been made
              to overdraw in excess of the borrowing limits approved by the Bank.
            </p>
            <p>
              2.7 The customer should comply with TN CyberTech Bank Limited security recommendations and directions as published on
              the website from time to time.
            </p>

            <h2>3. Unauthorised Use of the PIN and Password – Access Codes</h2>
            <p>
              3.1 The Bank deals with the customer remotely when using Digital Banking Channels (there is no face to face interaction),
              as such, the Customer authorizes the Bank to act on and accept all instructions and transactions that occur after the
              customers PIN, Password or OTP have been entered or applied. The Bank is entitled to and will proceed on the assumption
              that all such transactions have been authorized by the customer, even in circumstances where such transactions occur
              without the customers knowledge, consent or authority. The Customer must inform the Bank immediately if he/she knows or
              suspects that his/her access code(s) have been lost, stolen or may be subjected to unauthorised use.
            </p>
            <p>
              3.2 If any unauthorized person obtains the Access Codes in any manner whatsoever, such a person will be regarded as the
              Customer's duly authorized agent with full authority to use the Digital Banking Channels on the Customer's behalf, unless
              this is due to the Bank's negligence.
            </p>

            <h2>4. Indemnity and Warranty by the Customer</h2>
            <p>
              4.1 The Customer indemnifies the Bank against any damage, loss and/or consequential damage that the Bank may suffer as
              a result of incorrect, wrong, unauthorized and/or wrongful instructions or information given by the customer or any other
              person authorized or deemed to be authorized to act on behalf of the customer.
            </p>
            <p>
              4.2 The Customer hereby warrants to the Bank that the Customer has the required legal capacity to enter into and be bound
              by these Terms and Conditions.
            </p>

            <h2>5. Duties of the Customer</h2>
            <p>
              5.1 The Customer must ensure secure retention of his/her PIN, Password or OTP secret. The Customer is prohibited from
              disclosing the PIN, Password or OTP, to third parties to prevent access by unauthorized person.
            </p>
            <p>
              5.2 The Customer must take all reasonable precautions to prevent unauthorized use of the Digital Banking Channels and
              unauthorized access to the Account.
            </p>
            <p>
              5.3 If the Customer suspects that the PIN, Password or OTP has become compromised, the Customer must immediately notify
              the Bank and arrange to immediately change the PIN or Password.
            </p>
            <p>
              5.4 The Customer must provide the correct account number as well as the correct branch clearing code, where required, of
              all beneficiaries when instructing the Bank to make payments, pay accounts and to transfer funds to such beneficiaries or
              when accessing or carrying out any other transaction or service. The Bank is not obliged to, at any stage, verify an account
              number and branch clearing code against the name of a beneficiary.
            </p>
            <p>5.5 As a Customer of the Bank, the Customer agrees to:</p>
            <ul>
              <li>5.5.1 provide the Bank with accurate and up to date information;</li>
              <li>5.5.2 avoid over-indebtedness;</li>
              <li>
                5.5.3 take necessary steps to be informed about any banking product available from the Bank, including making
                comparisons, before subscribing to financial products and services;
              </li>
              <li>5.5.4 obtain clarifications where necessary;</li>
              <li>5.5.5 use the products or services of the Bank in line with the terms and conditions;</li>
              <li>5.5.6 fulfil its obligations in contractual relationship with the Bank;</li>
              <li>
                5.5.7 ensure records of transactions or communications between the Bank and itself such as card receipts, account
                statements and transaction statements are safeguarded or disposed of properly to avoid unauthorized access;
              </li>
              <li>5.5.8 take reasonable steps to prevent fraud;</li>
              <li>5.5.9 exercise due care when issuing a power of attorney or appointing an Authorized Signatory; and</li>
              <li>5.5.10 avoid using the account for money laundering and financing of terrorism purposes.</li>
            </ul>

            <h2>6. Other Applicable Agreements</h2>
            <p>
              Certain products and services that the customer uses or accesses via Digital Banking Channels such as the bank account or
              services that the customer accesses, the customers ATM Debit card and Credit card are subject to their own terms and
              conditions. This agreement (governing the use of Digital Banking Channels) must be read together with, and forms part of
              each product agreement. In the event of conflict between this agreement and such other terms, the provisions of such other
              terms will prevail to the extent of the conflict.
            </p>

            <h2>7. Fees</h2>
            <p>
              7.1 Any fees and charges in respect of the Digital Banking Channels will be debited to the Customer's nominated bank
              account (Billing Account). A copy can be obtained from{' '}
              <a href="https://tncybertechbank.co.zw/" style={{ color: 'rgb(174, 106, 6)' }}>https://tncybertechbank.co.zw/</a>{' '}
              or from any TN CyberTech Bank branch. Should the Bank be unable to recover any fees/charges from the nominated bank
              account on the due date due to insufficient funds or for any other reason whatsoever, the Bank shall be entitled to recover
              such fees/charges as and when the funds may become available in the customer's nominated bank account, alternatively from
              any other TN CyberTech Bank account belonging to the Customer.
            </p>
            <p>
              7.2 Should the Bank be unable to recover any fees/charges as per 7.1 above, the Bank reserves the right to suspend the
              Online and/or Mobile Banking service with immediate effect, with or without notice.
            </p>
            <p>
              7.3 The Bank may vary the fees/charges in respect of Digital Banking Channels by giving a month's notice of such
              amendments to the Customer by posting a notification of amendments on the website and selected media.
            </p>

            <h2>8. Availability of Electronic Channels Banking</h2>
            <p>
              8.1 The Digital Banking Channels will be available at all times, subject to the availability of the Internet and Mobile
              Networks connections and to any periods required for necessary maintenance of the Internet and Mobile networks connections.
            </p>
            <p>
              8.2 Should the Digital Banking Channels be unavailable for whatever reason, the Customer must use the Bank's other
              available service channels and take reasonable steps to minimize and/or prevent loss or risk.
            </p>

            <h2>9. Internet Requirements</h2>
            <p>
              9.1 Should the Customer obtain access to the Digital Banking Channels via the Internet, the customer must register with
              an Internet Service Provider before the commencement date.
            </p>
            <p>
              9.2 The Customer will be solely responsible for the acquisition, installation and maintenance of the connection to the
              Internet or any related costs or expenses will be borne by the Customer.
            </p>
            <p>
              9.3 Should the Internet software and hardware requirements be modified with a view to improving or upgrading the Internet,
              the resultant cost of any hardware, software or Internet connection required for use of the system will be for the
              Customer's own account.
            </p>
            <p>
              9.4 In the event that the Customer experiences problems with the Internet and Internet connection, it is the Customer's
              responsibility to liaise with the Internet Service Providers prior to contacting the Bank.
            </p>

            <h2>10. Mobile Telephone Requirements</h2>
            <p>
              10.1 Should the Customer obtain access to the Digital Banking Channels via the cell phone, the Customer must register
              with a Mobile Network Operator before the commencement date.
            </p>
            <p>
              10.2 The customer will be solely responsible for obtaining of the prescribed cell phone and the connection to the Mobile
              Network Operator and any related costs or expenses will be borne by the Customer.
            </p>
            <p>
              10.3 Should the cell phone requirements be modified with a view to improving or upgrading the Online Banking, the
              resultant costs of any new cell phone or service provider connection required so as to use the Digital Banking Channels
              will be for the Customer's own account.
            </p>
            <p>
              10.4 In the event that the Customers experience connectivity or other access related difficulties with the cell phone
              and/or Mobile Network Operator, it is the Customer's responsibility to liaise with the Mobile Network Operator prior
              to contacting the Bank.
            </p>

            <h2>11. Liability for Loss or Damage</h2>
            <p>11.1 The Customer acknowledges that the use of the Digital Banking Channels and the Account is at the Customer's own risk.</p>
            <p>11.2 The Bank will not be responsible for any damage, loss or consequential damage which the Customer may suffer as a result of:</p>
            <ul>
              <li>11.3 Any malfunction or defect in the hardware used by the Customer (which includes the personal computer or cell phone).</li>
              <li>11.4 Any defect in the software used by the Customer to gain access to the Digital Banking Channels.</li>
              <li>
                11.5 Any act or omission by the Internet or Mobile Network Operator or any defect in the Digital Banking Channels or
                any other medium by which access is gained to the system.
              </li>
              <li>11.6 The Digital Banking Channels being off-line or unavailable.</li>
              <li>11.7 Any industrial action.</li>
              <li>11.8 Any other circumstances not reasonably within the Bank's control.</li>
              <li>11.9 Erroneous, unauthorized, incomplete or unlawful instruction from the Customer.</li>
              <li>11.10 Unlawful or unauthorized access by another person(s).</li>
              <li>11.11 Incorrect or late execution or non-payment of any instruction given by the Customer, due to the circumstances set out in 11.3 to 11.10.</li>
            </ul>

            <h2>12. Intellectual Property</h2>
            <p>
              12.1 The Bank retains all copyright and other intellectual property rights in all material, including logos and other
              graphics and multimedia works published on or through this website.
            </p>
            <p>
              12.2 The customer is authorized to view and download a copy of these Terms and Conditions to a local hard drive or disk,
              print and make copies of such printouts, provided that the material is used for considering use of the Digital Banking
              Channels and for no other commercial purposes.
            </p>
            <p>
              12.3 Any reproduction of the Bank's proprietary material from the website or portion of it, must include the Bank's
              copyright notice in its entirety.
            </p>
            <p>
              12.4 Nothing on this website should be construed as granting any license or right to use any trademark without the
              Bank's prior written consent and/or the prior written consent of the third parties, as the case may be. The customer
              may not without the Bank's prior written consent, use the Bank's intellectual property or the intellectual property of
              third parties for any purposes whatsoever.
            </p>

            <h2>13. Termination, Suspension or Withdrawal of the Electronic Channels Banking</h2>
            <p>
              13.1 The Customer may terminate the Digital Banking Channels by giving the Bank 30 (thirty) days' written notice. The
              notice should be signed by the customer.
            </p>
            <p>
              13.2 The Bank is entitled, at its discretion, to terminate the Digital Banking Channels at any time the Bank deems it necessary.
            </p>
            <p>
              13.3 In order to protect the Customer, the Bank and the banking systems, the Bank is entitled to immediately suspend or
              withdraw all or part of its Digital Banking Channels if the Channel is being used contrary to the Terms and Conditions of
              this agreement; the Bank has reasonable grounds to believe that the channel may be used negligently, illegally or
              fraudulently; or the Bank believes that the security of the system used to provide the Digital Banking Channels may be
              compromised.
            </p>
            <p>
              13.4 In the event that the Digital Banking Channels has not been used for a period of 6 (six) months or longer, the Bank
              reserves the right to terminate the agreement without prior notice. The Customer may reapply for the Digital Banking
              Channels at any time.
            </p>
            <p>
              13.5 The customer is liable for all transactions and/or obligations (and related charges) which are incurred up to and
              including the date of termination.
            </p>

            <h2>14. Protection of Data and Privacy</h2>
            <p>
              14.1 The Customer agrees to be bound by the Bank's privacy statement, as may from time to time be updated or varied by
              the Bank in relation to any personal data protection laws and regulations of Zimbabwe and as posted on the website of
              the Bank and agrees that the statement shall apply generally to the Bank's dealing with the Customer's personal data.
            </p>
            <p>
              14.2 The Bank will treat all the customer's personal data as private and confidential even when the Customer ceases to
              be a Customer of the Bank. Personal data will only be used for specific purposes and with prior consent of the Customer,
              except where the law stipulates otherwise.
            </p>
            <p>
              14.3 The Customer's personal data will not be disclosed to any third parties except where the law stipulates the personal
              data should be disclosed, where it is in the public interest to disclose; where the Bank's interests require disclosure;
              and where disclosure is made at the Customer's request or where the Customer has given the Bank written consent.
            </p>

            <h2>15. General</h2>
            <p>
              All information on this website is only intended to provide the Customer with general information about the Bank, Bank
              products and services and the Bank will endeavour to ensure that the information provided is up to date. The Bank will
              periodically amend, add, delete, update or alter the information, including without limitation, the Terms and Conditions
              of use at the website without notice. Further, the Bank assumes no responsibility for any errors or omissions in the
              content of the website. Users agree to indemnify, defend and hold the Bank harmless from any liability, loss, claim and
              expense, including legal fees related to a user's violation of these Terms and Conditions or unauthorized use of the
              services and information provided on this website. The Terms and Conditions will be governed by and construed in
              accordance with the applicable laws of the Republic of Zimbabwe and users agree that all legal proceedings relating to
              the matters herein shall be adjudicated solely in the courts of the Republic of Zimbabwe. To the extent that any portion
              of these Terms and Conditions shall be determined to be unenforceable by a court of competent jurisdiction, such portion
              will be modified by the court solely to the extent necessary to cause such portion to be enforceable, and these Terms and
              Conditions as so modified will remain in full force and effect. Any waiver of any provisions contained in these Terms and
              Conditions by the Bank shall not be deemed to be a waiver of any other right, term or provision of these Terms and Conditions.
            </p>

            <h2>Complaint Handling</h2>
            <p>
              If you are dissatisfied with the service that you receive from TN CyberTech Bank, you have a right to raise a complaint
              through any of our branches in person, by telephone, email, fax, letter or complete a complaints register leaflet which
              you can obtain from any of our branches. We hope to resolve your complaints within 48 hours. If the complaint is not
              resolved within 48 hours you may escalate to the Customer Experience Department at TN CyberTech Bank Head Office on{' '}
              <strong>0808 8888</strong> from Econet lines. Alternatively, you may email us on{' '}
              <a href="mailto:customerservice@tncybertechbank.co.zw" style={{ color: 'rgb(174, 106, 6)' }}>
                customerservice@tncybertechbank.co.zw
              </a>.
            </p>

            <div style={{
              marginTop: '2rem',
              padding: '1.5rem',
              background: 'linear-gradient(135deg, rgba(255, 222, 74, 0.1) 0%, rgba(174, 106, 6, 0.05) 100%)',
              border: '1px solid rgba(255, 222, 74, 0.3)',
              borderRadius: '12px',
            }}>
              <p style={{ margin: 0, fontStyle: 'italic', color: '#4b5563' }}>
                I/We have read and understood the Terms and Conditions which contain the policy summaries and other Account Information.
              </p>
            </div>

          </div>
        </div>
      </section>

      <Footer />
    </div>
  )
}

export default DigitalBankingTerms
