name: tn-landing
static_sites:
  - name: tn-landing
    build_command: npm run build
    output_dir: dist
    routes:
      - path: /
        preserve_path_prefix: true
    catchall_document: index.html
    cors:
      allow_origins:
        - exact: "*"
    headers:
      - path: /*
        headers:
          Strict-Transport-Security: max-age=31536000; includeSubDomains
          X-Frame-Options: SAMEORIGIN
          X-Content-Type-Options: nosniff
          Referrer-Policy: strict-origin-when-cross-origin
          Permissions-Policy: accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()
          Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self' https:; frame-ancestors 'self'
