alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
domains:
- domain: tncybertechbank.co.zw
  type: PRIMARY
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: tn-tn-landing
    match:
      authority:
        exact: ""
      path:
        prefix: /
  - component:
      name: tn-api
    match:
      path:
        prefix: /api
maintenance: {}
name: tn-app
region: blr
services:
- environment_slug: node-js
  github:
    branch: main
    deploy_on_push: true
    repo: Tinashe77/TN
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  name: tn-api
  run_command: npm start
  source_dir: tn-api
  envs:
  - key: SMTP_USER
    value: tncustomer@tncybertechbank.co.zw
    type: SECRET
  - key: SMTP_PASS
    value: EV_VALUE_SET_IN_DASHBOARD
    type: SECRET
static_sites:
- build_command: |
    npm ci && npm run build
  catchall_document: index.html
  cors:
    allow_origins:
    - exact: "*"
  environment_slug: node-js
  github:
    branch: main
    deploy_on_push: true
    repo: Tinashe77/TN
  name: tn-tn-landing
  output_dir: dist
  source_dir: tn-landing
